### ISSUE TITLE
herotalentbuilds.json is outdated

### ISSUE THREAD

**Issue by sergebruni** [ESWAT/stormchaser#1]
that file last update was on Sat Sep 05 2015 14:50:50 GMT+0000 (UTC)
and that link from Heroes of the Storm - Hero Best Talent Build, well Kimono shut down on February 29th, 2016 and the cloud service has been discontinued.

**Comment by ESWAT** [comment]
Sorry, realize this project is very outdated. I don’t play HotS anymore and don’t see myself fixing the issue.
